In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2], index=list('TUV'))
ser2 = Series([3,4], index=list('XY'))

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [11]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [12]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'], axis=1)

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [17]:
dframe1 = DataFrame(np.random.randn(4,3), columns=list('XYZ'))

In [18]:
dframe1

X         Y         Z
0 -1.232679  0.151629 -0.434128
1  2.212532 -0.738224 -0.519460
2 -1.852997  2.000119 -1.402064
3 -1.420131  0.482604  1.113500

In [19]:
dframe2 = DataFrame(np.random.randn(3,3), columns = list('YQX'))

In [20]:
dframe2

Y         Q         X
0  2.822095  0.899935  0.230267
1  1.244708 -0.375853 -0.558328
2 -1.481959  0.483352  0.532279

In [22]:
pd.concat([dframe1, dframe2])

X         Y         Z         Q
0 -1.232679  0.151629 -0.434128       NaN
1  2.212532 -0.738224 -0.519460       NaN
2 -1.852997  2.000119 -1.402064       NaN
3 -1.420131  0.482604  1.113500       NaN
0  0.230267  2.822095       NaN  0.899935
1 -0.558328  1.244708       NaN -0.375853
2  0.532279 -1.481959       NaN  0.483352

In [23]:
pd.concat([dframe1, dframe2], ignore_index=True)

X         Y         Z         Q
0 -1.232679  0.151629 -0.434128       NaN
1  2.212532 -0.738224 -0.519460       NaN
2 -1.852997  2.000119 -1.402064       NaN
3 -1.420131  0.482604  1.113500       NaN
4  0.230267  2.822095       NaN  0.899935
5 -0.558328  1.244708       NaN -0.375853
6  0.532279 -1.481959       NaN  0.483352