In [1]:
import numpy as np

In [2]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [6]:
np.arcsin(arr)

/Users/fujiken/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


array([0.        , 1.57079633,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan])

In [7]:
A=np.random.randn(10)
A

array([-1.10198616, -0.05049095, -0.6627373 , -1.43256262, -0.08504027,
       -1.19761577,  0.79017195,  0.1469296 , -1.32353381,  0.03048301])

In [8]:
rng=np.random.default_rng()
B=rng.standard_normal(10)
B

array([-0.06099079, -0.17249306, -0.43766492, -0.78516159,  0.98574601,
       -0.03985532,  1.59880103,  0.43634516,  0.22709702, -1.20831616])

In [9]:
np.add(A,B)

array([-1.16297696, -0.22298401, -1.10040222, -2.21772422,  0.90070574,
       -1.2374711 ,  2.38897298,  0.58327476, -1.09643679, -1.17783315])

In [10]:
np.maximum(A,B)

array([-0.06099079, -0.05049095, -0.43766492, -0.78516159,  0.98574601,
       -0.03985532,  1.59880103,  0.43634516,  0.22709702,  0.03048301])